import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
    Comparison,
    SequenceMatcher,
    SimilarityEngine,
    SimilarityThresholds,
} from "../src/features/crosspost/similarity";

const FIXTURE_DIR = join(__dirname, "fixtures", "similarity");

/**
 * Golden vectors from CPython's difflib (see generate_sequence_vectors.py in
 * the fixture dir). The TS SequenceMatcher must match these bit-for-bit —
 * crosspost thresholds were tuned against exact difflib ratios.
 */
interface RatioVector {
    name: string;
    a: string;
    b: string;
    ratio: number;
}
const ratioVectors: { cases: RatioVector[] } = JSON.parse(
    readFileSync(join(FIXTURE_DIR, "sequence_ratio_vectors.json"), "utf8"),
);

/**
 * Characterization fixture capturing the engine's observed behavior at commit
 * 281e341 (pre-refactor baseline), generated by running the engine itself and
 * checked in. It exists to prove refactors bit-identical — REGENERATING IT
 * AFTER A BEHAVIOR CHANGE DEFEATS ITS PURPOSE. If a deliberate scoring change
 * is ever made (coordinated with VRDHelper + threshold re-tuning), regenerate
 * consciously and say so in the commit message.
 */
interface CharacterizationCase {
    name: string;
    input: string;
    normalized: string;
    tokens: string[];
    deltaTokens: string[];
}
interface NgramCase {
    text: string;
    grams: Array<[string, number]>;
}
interface PairCase {
    current: string;
    prior: string;
    comparison: Comparison;
}
const characterization: {
    cases: CharacterizationCase[];
    ngramCases: NgramCase[];
    pairs: PairCase[];
} = JSON.parse(readFileSync(join(FIXTURE_DIR, "characterization.json"), "utf8"));

describe("SequenceMatcher — difflib parity", () => {
    for (const vec of ratioVectors.cases) {
        it(`matches Python ratio exactly: ${vec.name}`, () => {
            const matcher = new SequenceMatcher();
            matcher.setSeqs(vec.a, vec.b);
            expect(matcher.ratio()).toBe(vec.ratio);
        });
    }

    it("gives identical results when one instance is reused across pairs (b-caching path)", () => {
        const shared = new SequenceMatcher();
        for (const vec of ratioVectors.cases) {
            shared.setSeqs(vec.a, vec.b);
            expect(shared.ratio()).toBe(vec.ratio);
            // Same b again with a different a exercises the chainB cache.
            shared.setSeqs(vec.b, vec.b);
            expect(shared.ratio()).toBe(1.0);
        }
    });

    it("a prebuilt index passed to setSeqs gives identical ratios on every vector", () => {
        for (const vec of ratioVectors.cases) {
            const matcher = new SequenceMatcher();
            matcher.setSeqs(vec.a, vec.b, SequenceMatcher.buildIndex(vec.b));
            expect(matcher.ratio(), vec.name).toBe(vec.ratio);
        }
    });

    it("fingerprint().seqIndex is exactly buildIndex(normalized)", () => {
        const engine = new SimilarityEngine();
        const fp = engine.fingerprint("my quest3 keeps disconnecting from virtualdesktop every few minutes");
        expect(fp.seqIndex).toEqual(SequenceMatcher.buildIndex(fp.normalized));
    });

    it("autojunk empties b2j for all-popular strings, but the extension loops still match the prefix", () => {
        // "a"*250 vs "a"*240: the DP finds nothing (every 'a' is popular junk in
        // b2j) yet findLongestMatch's forward extension matches all 240 common
        // chars from (alo, blo) — difflib does the same: 2*240/490.
        const vec = ratioVectors.cases.find(c => c.name === "autojunk-all-popular");
        expect(vec?.ratio).toBe(480 / 490);
    });
});

describe("SimilarityEngine — characterization (bit-identical to 281e341 baseline)", () => {
    const engine = new SimilarityEngine();

    for (const c of characterization.cases) {
        it(`normalize/tokenize: ${c.name}`, () => {
            const normalized = engine.normalizeContent(c.input);
            expect(normalized).toBe(c.normalized);
            expect([...engine.tokenize(normalized)].sort()).toEqual(c.tokens);
            expect(engine.tokenizeForDelta(c.input)).toEqual(c.deltaTokens);
        });
    }

    for (const n of characterization.ngramCases) {
        it(`charNgrams (content AND insertion order): ${JSON.stringify(n.text)}`, () => {
            // Order matters: the cosine dot-product iterates in insertion order,
            // so gram order is part of the float-exactness contract.
            expect([...engine.charNgrams(n.text).entries()]).toEqual(n.grams);
        });
    }

    it("compare() reproduces every fixture pair exactly", () => {
        const byName = new Map(characterization.cases.map(c => [c.name, engine.fingerprint(c.input)]));
        for (const pair of characterization.pairs) {
            const current = byName.get(pair.current)!;
            const prior = byName.get(pair.prior)!;
            expect(engine.compare(current, prior), `${pair.current} vs ${pair.prior}`).toEqual(pair.comparison);
        }
    });
});

describe("SimilarityEngine — behavior", () => {
    const engine = new SimilarityEngine();

    // Gate-isolation thresholds: all three algorithms trivially trigger so the
    // tests below exercise ONLY the length / length-ratio gates.
    const openThresholds: SimilarityThresholds = {
        sequenceRatioThreshold: 0,
        charCosineThreshold: 0,
        jaccardThreshold: 0,
        minNormalizedLength: 5,
        lengthRatioThreshold: 1.5,
        minAlgorithmsToMatch: 1,
    };

    it("identical messages trigger all three algorithms and match", () => {
        const t: SimilarityThresholds = {
            sequenceRatioThreshold: 0.8,
            charCosineThreshold: 0.8,
            jaccardThreshold: 0.5,
            minNormalizedLength: 20,
            lengthRatioThreshold: 1.8,
            minAlgorithmsToMatch: 2,
        };
        const fp = engine.fingerprint("my quest3 keeps disconnecting from virtualdesktop every few minutes");
        const c = engine.compare(fp, fp);
        expect(engine.countAlgorithmsTriggered(c, t)).toBe(3);
        expect(engine.meetsSimilarityThresholds(fp, fp, c, t)).toBe(true);
    });

    it("countAlgorithmsTriggered counts each algorithm independently", () => {
        const t: SimilarityThresholds = {
            sequenceRatioThreshold: 0.8,
            charCosineThreshold: 0.8,
            jaccardThreshold: 0.5,
            minNormalizedLength: 0,
            lengthRatioThreshold: 99,
            minAlgorithmsToMatch: 2,
        };
        const c: Comparison = {
            sequenceRatio: 0.9,
            jaccard: 0.4,
            charCosine: 0.85,
            confidence: 0,
            lengthRatio: 1,
            newContentRatio: 0,
        };
        expect(engine.countAlgorithmsTriggered(c, t)).toBe(2);
    });

    it("the min-normalized-length gate rejects short messages even when scores are perfect", () => {
        const fp = engine.fingerprint("hi there");
        const c = engine.compare(fp, fp);
        expect(engine.meetsSimilarityThresholds(fp, fp, c, { ...openThresholds, minNormalizedLength: 50 })).toBe(false);
        expect(engine.meetsSimilarityThresholds(fp, fp, c, { ...openThresholds, minNormalizedLength: 5 })).toBe(true);
    });

    it("the length-ratio gate rejects pairs of very different size", () => {
        const long = engine.fingerprint("quest3 wifi keeps dying on the dedicated router every session");
        const short = engine.fingerprint("quest3 wifi dying");
        const c = engine.compare(long, short);
        expect(c.lengthRatio).toBeGreaterThan(1.5);
        expect(engine.meetsSimilarityThresholds(long, short, c, openThresholds)).toBe(false);
        expect(engine.meetsSimilarityThresholds(long, short, c, { ...openThresholds, lengthRatioThreshold: 99 })).toBe(
            true,
        );
    });

    it("empty-vs-empty compares as (seq 1.0, jaccard 1.0, cosine 0.0) — the length gate is the real guard", () => {
        const a = engine.fingerprint("   ");
        const b = engine.fingerprint("");
        const c = engine.compare(a, b);
        expect(c).toEqual({
            sequenceRatio: 1.0,
            jaccard: 1.0,
            charCosine: 0.0,
            confidence: engine.computeConfidence(1.0, 0.0, 1.0),
            lengthRatio: 1.0,
            newContentRatio: 0.0,
        });
        expect(engine.meetsSimilarityThresholds(a, b, c, openThresholds)).toBe(false);
    });

    it("newContentRatio: empty current → 0, empty prior → 1, else the novel fraction", () => {
        const empty = engine.fingerprint("");
        const prior = engine.fingerprint("quest3 wifi router");
        const current = engine.fingerprint("quest3 wifi bitrate codec");
        expect(engine.compare(empty, prior).newContentRatio).toBe(0.0);
        expect(engine.compare(current, empty).newContentRatio).toBe(1.0);
        // deltaTokens of current: [quest3, wifi, bitrate, codec]; 2 of 4 novel.
        expect(engine.compare(current, prior).newContentRatio).toBe(0.5);
    });
});

/**
 * These lock in ported-verbatim normalization quirks (see the comment block in
 * normalizeContent). If one of these fails because you reordered normalization
 * steps: that is a SCORING CHANGE — it needs cross-bot coordination with
 * VRDHelper and threshold re-tuning, not a drive-by fix.
 */
describe("SimilarityEngine — ported normalization quirks (do not 'fix' casually)", () => {
    const engine = new SimilarityEngine();

    it("lines whose first char becomes a space (bullets, quotes) are deleted wholesale", () => {
        expect(engine.normalizeContent("* bullet one\n* bullet two\nplain trailing line")).toBe("plain trailing line");
    });

    it("custom-emoji removal is dead code — the '>' is stripped first, so ids leak into tokens", () => {
        expect(engine.normalizeContent("<a:wave:112233>")).toBe("a wave 112233");
    });

    it("code-fence removal is dead code — backticks are stripped first, so code content leaks", () => {
        expect(engine.normalizeContent("```js\nconst x = 1;\n```\nWhy does `adb devices` show nothing?")).toBe(
            "const x 1 why does adb devices show nothing",
        );
    });

    it("the canonical '2.4ghz' form is immediately re-split by the punctuation strip", () => {
        expect(engine.normalizeContent("2.4 GHz")).toBe("2 4ghz");
        // ...while the delta tokenizer keeps the dot:
        expect(engine.tokenizeForDelta("2.4 GHz")).toEqual(["2.4ghz"]);
    });
});
